services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - api/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev-network

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - api/.env
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy --schema ./prisma/schema.prisma && npm run start:dev"
    networks:
      - dev-network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
    env_file:
      - client/.env
    restart: unless-stopped
    networks:
      - dev-network

volumes:
  postgres:

networks:
  dev-network:
    driver: bridge
